name: CI

on: 
  push:
    paths:
      - 'libs/**'
      - 'source/**'
      - meson.build
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependent packages
        run: sudo apt install clang meson ninja-build cmake libglfw3-dev libfmt-dev libtbb-dev

      - name: Generate build directory
        run: cd $GITHUB_WORKSPACE && meson builddir

      - name: Build the engine
        run: cd $GITHUB_WORKSPACE/builddir && ninja
